-- new-pay OnlineStore(GPS) schema, 依 SD 4.7 Schema調整
-- H2 MODE=Oracle

-- 4.7.1 MWP_SMS_GPS
CREATE TABLE MWP_SMS_GPS (
    ID                  VARCHAR2(20) NOT NULL,
    CREATE_TIME         VARCHAR2(14) NOT NULL,
    SOURCE_SMS_CONTENT  VARCHAR2(128) NOT NULL,
    SOURCE_MSISDN       VARCHAR2(20) NOT NULL,
    REQ_CONTENT         VARCHAR2(128),
    STATUS              VARCHAR2(2) NOT NULL,       -- D:Done F:fail
    REQ_TIME            VARCHAR2(21),
    RET_CODE            VARCHAR2(16),
    RET_DESCRIPTION     VARCHAR2(128),
    PRIMARY KEY (ID)
);

-- 4.7.2 MWP_GPS_SOAP_PROVISIONING
CREATE TABLE MWP_GPS_SOAP_PROVISIONING (
    ID              VARCHAR2(32) NOT NULL,
    CREATE_TIME     VARCHAR2(14) NOT NULL,
    REQUEST_XML     VARCHAR2(256) NOT NULL,     -- spec 就是 256, XML 存不下, 程式先截斷處理
    CORRELATION_ID  VARCHAR2(20) NOT NULL,
    OUT             VARCHAR2(20) NOT NULL,
    PROV_RESULT     VARCHAR2(20),
    IS_PROVISIONED  VARCHAR2(20),
    RESP_XML        VARCHAR2(256),
    PRIMARY KEY (ID)
);

-- 4.7.3 MWP_GPS_SOAP_AUTH
CREATE TABLE MWP_GPS_SOAP_AUTH (
    ID                  VARCHAR2(32) NOT NULL,
    CREATE_TIME         VARCHAR2(14) NOT NULL,
    REQUEST_XML         VARCHAR2(256) NOT NULL,
    CORRELATION_ID      VARCHAR2(20) NOT NULL,
    PURCHASE_TIME       VARCHAR2(21) NOT NULL,
    OUT                 VARCHAR2(20) NOT NULL,
    PAYMENT_DESCRIPTION VARCHAR2(128) NOT NULL,
    MERCHANT_CONTACT    VARCHAR2(128) NOT NULL,
    PRICE               VARCHAR2(21) NOT NULL,
    ROUNDED_PRICE       NUMBER(8,0) NOT NULL,
    AUTH_RESULT         VARCHAR2(20),
    AUTH_TXID           VARCHAR2(20),
    RESP_XML            VARCHAR2(256),
    PRIMARY KEY (ID)
);

-- 4.7.4 MWP_GPS_REQ_LOG
CREATE TABLE MWP_GPS_REQ_LOG (
    REQ_ID          VARCHAR2(32) NOT NULL,
    CREATE_TIME     VARCHAR2(14) NOT NULL,
    FILE_NAME       VARCHAR2(80) NOT NULL,      -- spec 寫 20 但檔名根本放不下, 先改 80
    STATUS          VARCHAR2(2) NOT NULL,       -- I/P/PD/F/D
    RESP_TIME       VARCHAR2(14),
    RESP_FILE_NAME  VARCHAR2(80),
    LAST_MOD_TIME   VARCHAR2(14) NOT NULL,
    PRIMARY KEY (REQ_ID)
);

-- 4.7.5 MWP_GPS_REQ_DETAIL (spec 說 REQ_ID 是 pKey 但一個檔有多筆明細, 所以沒放 PK)
CREATE TABLE MWP_GPS_REQ_DETAIL (
    REQ_ID              VARCHAR2(32) NOT NULL,
    REQ_TYPE            VARCHAR2(128) NOT NULL,
    REQ_TIMESTAMP       VARCHAR2(21) NOT NULL,
    CORRELATION_ID      VARCHAR2(64) NOT NULL,
    BILLING_AGREEMENT_ID VARCHAR2(64) NOT NULL,
    RESP_TIMESTAMP      VARCHAR2(21),
    RESULT_CODE         VARCHAR2(128),
    MESSAGE             VARCHAR2(1024)
);
CREATE INDEX IDX_GPS_REQ_ORDERNO_TYPE ON MWP_GPS_REQ_DETAIL (CORRELATION_ID, REQ_TYPE);

-- 4.7.6 MWP_CP_RECON_DAILY_LOG
CREATE TABLE MWP_CP_RECON_DAILY_LOG (
    RECON_ID        VARCHAR(20) NOT NULL,
    RECON_SEQ_NUM   VARCHAR(5) NOT NULL,
    MERCHANT_ID     VARCHAR2(20) NOT NULL,
    FILE_NAME       VARCHAR2(80) NOT NULL,
    CP_TX_DT        VARCHAR2(8) NOT NULL,
    CREATE_TIME     VARCHAR2(14) NOT NULL,
    STATUS          VARCHAR2(2) NOT NULL
);

-- 4.7.7 MWP_CP_RECON_DAILY_DETAIL
CREATE TABLE MWP_CP_RECON_DAILY_DETAIL (
    RECON_ID            VARCHAR2(20) NOT NULL,
    RECON_SEQ_NUM       VARCHAR(5) NOT NULL,
    MERCHANT_ID         VARCHAR2(20) NOT NULL,
    BILLING_AGREEMENT_ID VARCHAR2(64) NOT NULL,
    CORRELATION_ID      VARCHAR2(64),
    SQE_NUM             NUMBER(8,0) NOT NULL,
    TXID                VARCHAR2(20),
    STATUS              VARCHAR2(128),
    ITEM_PRICE          VARCHAR2(21),
    TAX                 VARCHAR2(21),
    TOTAL_AMOUNT        VARCHAR2(21),
    ROUND_AMOUNT        NUMBER(8,0),
    CURRENCY            VARCHAR2(4),
    LAST_EVENT          VARCHAR2(128),
    TIMESTAMP           VARCHAR2(21),
    EVENT_RESPONSE      VARCHAR2(128),
    EVENT_RESPONSE_DESCRIPTION VARCHAR2(1024),
    CREATE_TIME         VARCHAR2(14) NOT NULL,
    RECON_RESULT        VARCHAR2(3),
    RECON_MESSAGE       VARCHAR2(80)
);

-- 4.7.8 MWP_CP_RECON_DAILY_SUMMARY (CP_TOTAL_CONUT 拼字照 spec)
CREATE TABLE MWP_CP_RECON_DAILY_SUMMARY (
    RECON_ID            VARCHAR(20) NOT NULL,
    MERCHANT_ID         VARCHAR2(20) NOT NULL,
    RECON_RESULT_SUMMARY VARCHAR2(1),
    DIFF_COUNT          NUMBER(8,0),
    CP_TX_DT            VARCHAR2(8) NOT NULL,
    CP_TOTAL_CONUT      NUMBER(8,0),
    NEWPAY_TOTAL_COUNT  NUMBER(8,0),
    CP_FILE_NAME        VARCHAR2(80),
    PRIMARY KEY (RECON_ID)
);

-- 4.7.9 MWP_CP_RECON_MONTHLY_LOG
CREATE TABLE MWP_CP_RECON_MONTHLY_LOG (
    RECON_ID        VARCHAR(20) NOT NULL,
    RECON_SEQ_NUM   VARCHAR(5) NOT NULL,
    MERCHANT_ID     VARCHAR2(20) NOT NULL,
    FILE_NAME       VARCHAR2(80) NOT NULL,
    CP_TX_DT        VARCHAR2(8) NOT NULL,
    CREATE_TIME     VARCHAR2(14) NOT NULL,
    STATUS          VARCHAR2(2) NOT NULL
);

-- 4.7.10 MWP_CP_RECON_MONTHLY_DETAIL
CREATE TABLE MWP_CP_RECON_MONTHLY_DETAIL (
    RECON_ID            VARCHAR2(20) NOT NULL,
    RECON_SEQ_NUM       VARCHAR(5) NOT NULL,
    MERCHANT_ID         VARCHAR2(20) NOT NULL,
    BILLING_AGREEMENT_ID VARCHAR2(64) NOT NULL,
    CORRELATION_ID      VARCHAR2(64),
    SQE_NUM             NUMBER(8,0) NOT NULL,
    TXID                VARCHAR2(20),
    EVENT               VARCHAR2(128),
    ITEM_PRICE          VARCHAR2(21),
    TAX                 VARCHAR2(21),
    TOTAL_AMOUNT        VARCHAR2(21),
    ROUND_AMOUNT        NUMBER(8,0),
    CURRENCY            VARCHAR2(4),
    TIMESTAMP           VARCHAR2(21),
    CREATE_TIME         VARCHAR2(14) NOT NULL,
    RECON_RESULT        VARCHAR2(3),
    RECON_MESSAGE       VARCHAR2(80)
);

-- 4.7.11 MWP_CP_RECON_MONTHLY_SUMMARY
CREATE TABLE MWP_CP_RECON_MONTHLY_SUMMARY (
    RECON_ID            VARCHAR(20) NOT NULL,
    MERCHANT_ID         VARCHAR2(20) NOT NULL,
    CP_TX_DT            VARCHAR2(8) NOT NULL,
    CP_TOTAL_CONUT      NUMBER(8,0),
    NEWPAY_TOTAL_COUNT  NUMBER(8,0),
    CP_DETAIL_FILE_NAME VARCHAR2(80),
    CP_SUMMARY_FILE_NAME VARCHAR2(80),
    PRIMARY KEY (RECON_ID)
);

-- 4.7.13 MWP_GPS_TOS (spec 是 BLOB, 這裡先用 CLOB 存文字)
CREATE TABLE MWP_GPS_TOS (
    MERCHANT_ID     VARCHAR2(10) NOT NULL,
    TOS_VERSION     NUMBER(8,0) DEFAULT 1 NOT NULL,
    TOS_URL         VARCHAR2(256) NOT NULL,
    TOS_CONTENT     CLOB NOT NULL,
    TOS_NOTE        VARCHAR2(1024),
    TOS_MODIFIED_DATE VARCHAR2(14) NOT NULL,
    TOS_START_DATE  VARCHAR2(14) NOT NULL
);

-- 4.7.14 ADD Sequence: gpsProvTXSeq
CREATE SEQUENCE GPSPROVTXSEQ START WITH 1000000001;

-- ======== 既有系統 tables (只建這次會用到的欄位) ========

-- 4.7.15 MWP_USER (新增欄位 CSP_PAID_TYPE)
CREATE TABLE MWP_USER (
    ACC_ID          VARCHAR2(60) NOT NULL,
    MSISDN          VARCHAR2(20) NOT NULL,
    CSPUID          VARCHAR2(20),
    PAID_TYPE       VARCHAR2(2),
    CSP_PAID_TYPE   VARCHAR2(2),
    GSM_STATUS      VARCHAR2(10),
    ACC_LOCK        VARCHAR2(1),
    ROC_ID          VARCHAR2(10),
    STATUS          VARCHAR2(2),
    PRIMARY KEY (ACC_ID)
);

-- 4.7.16 MWP_PAY_TRANS (Add reference / auth_dt)
CREATE TABLE MWP_PAY_TRANS (
    TXID            VARCHAR2(15) NOT NULL,
    MERCHANT_ID     VARCHAR2(20) NOT NULL,
    ACC_ID          VARCHAR2(60) NOT NULL,
    SERVICE_ID      VARCHAR2(20),
    CHANNEL         VARCHAR2(10),
    AMOUNT          NUMBER(8,0) NOT NULL,
    CURRENCY        VARCHAR2(4),
    TX_STATUS       VARCHAR2(2) NOT NULL,
    RETURN_CODE     VARCHAR2(32),
    RETURN_MSG      VARCHAR2(128),
    TX_DT           VARCHAR2(14) NOT NULL,
    AUTH_DT         VARCHAR2(14),
    BILL_CSPTIME    VARCHAR2(14),
    MEMO            VARCHAR2(64),
    MERCHANDIZE_NAME VARCHAR2(60),
    REFERENCE       VARCHAR2(128),
    MODIFY_DATE     VARCHAR2(14),
    PRIMARY KEY (TXID)
);

-- 4.7.17 MWP_PAY_REFUND (Add refund_date)
CREATE TABLE MWP_PAY_REFUND (
    TXID            VARCHAR2(15) NOT NULL,
    MERCHANT_ID     VARCHAR2(20),
    AMOUNT          NUMBER(8,0) NOT NULL,
    REFUND_STATUS   VARCHAR2(2) NOT NULL,
    REFUND_DATE     VARCHAR2(14),
    CREATE_TIME     VARCHAR2(14) NOT NULL,
    RETURN_CODE     VARCHAR2(32),
    RETURN_MSG      VARCHAR2(128)
);

CREATE TABLE MWP_BATCH_DEDUCTION_DETAIL (
    ID              VARCHAR2(32) NOT NULL,
    TXID            VARCHAR2(15) NOT NULL,
    TYPE            VARCHAR2(20) NOT NULL,
    ACC_ID          VARCHAR2(60) NOT NULL,
    SERVICE_ID      VARCHAR2(20),
    CHANNEL         VARCHAR2(10),
    AMOUNT          NUMBER(8,0) NOT NULL,
    STATUS          VARCHAR2(2) NOT NULL,      -- B: 待打包 S: 已送CSP D: 扣款成功 F: 扣款失敗
    CREATE_TIME     VARCHAR2(14) NOT NULL,
    MODIFY_DATE     VARCHAR2(14),
    PRIMARY KEY (ID)
);

-- 4.7.18 MWP_MERCHANT_BANK_ACC (Add IS_DOMESTIC)
CREATE TABLE MWP_MERCHANT_BANK_ACC (
    MERCHANT_ID     VARCHAR2(20) NOT NULL,
    BANK_CODE       VARCHAR2(3) NOT NULL,
    BANK_ACC        VARCHAR2(16) NOT NULL,
    CURRENCY        VARCHAR2(4),
    IS_DOMESTIC     VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    STATUS          VARCHAR2(2)
);

-- 4.3.2 Step 6 提到的 provision pool (目前程式只寫入沒人消化, 先放著)
CREATE TABLE MWP_BATCH_PROVISION_POOL (
    OUT             VARCHAR2(20) NOT NULL,
    CREATE_TIME     VARCHAR2(14) NOT NULL,
    STATUS          VARCHAR2(2) NOT NULL
);
